### PR TITLE
Checking pg_control file existence before restore

### PR DESCRIPTION
**Pull request by egashira-yusuke**
This is correction for #114
The target is PostgreSQL 11 and later.

In restore processing, pg_rman read the pg_control file from target database cluster.
However, if the database cluster had been deleted completely, pg_rman restore was failed because of calling get_controlfile().
The information of pg_control file in old database cluster is used only by --check option.
It is not necessarily required for database restore.

This patch introduces file existence check about old database cluster's pg_control file in restore processing.
If pg_control file is not found in restore process, it uses default value of PostgreSQL's configuration.

### CODE REVIEW

**Comment by MoonInsung** [comment]
Dear egashira-yusuke.

Thank you for creating the patch.
As your opinion did not check the existence of the pg_control file, so side effects occurred.
In addition to this part, I'm found that when getting values ​​from the pg_control file, it was not checked that the existence of the pg_control file.
Probably we will need to check for the existence of pg_contrl file in all parts like your patch.
So I'll make sure to create a new patch after considering. (After PG96 branch)

This patch is a merge and will be applied to the master branch later.

Thank you.

Best regards.
Moon.

**Comment by MoonInsung** [comment]
Hmm .. I thought of a problem suddenly after merged.
If the WAL segment size is not DEFAULT_XLOG_SEG_SIZE, the WAL required for recovery cannot be found correctly.
In such a case, a problem that cannot be recovery and the existing PGDATA will be deleted, which may cause a big problem.
Probably it is better to interrupt the restore operation while sending an ERROR message instead of WARNING.
What do you think?

**Comment by egashira-yusuke** [comment]
> If the WAL segment size is not DEFAULT_XLOG_SEG_SIZE, the WAL required for recovery cannot be found correctly.

Yes, this correction contains such problem.
However, it is not problem in recovery task of current version's pg_rman, I think.

In recovery task, pg_rman uses the value of wal_segment_size from pg_control to "check" the recovery parameters and required resources. The wal_segment_size is not used for actual recovery job.
Also, if the PostgreSQL's DEFAULT_XLOG_SEG_SIZE is changed in building server, it will assimilate in building pg_rman because DEFAULT_XLOG_SEG_SIZE is defined in PostgreSQL's include file "include/pg_config.h".

The pattern of critical corruption is satisfies following conditions.
- The old PostgreSQL server is built with "--with-wal-segsize".
- The backup data was created by pg_rman with old PostgreSQL server.
- Current PostgreSQL server and pg_rman is built with "--with-wal-segsize", that is different from backuped environment.
This pattern is unrealistic.

Of course, if the value from pg_control is used for actual backup or recovery jobs, it should not use DEFAULT value. In that case, the value should be get from actual database insatance.
- In backup : get from target instance's pg_control.
- In recovery: get from backuped data.
I didn't modify the other parts because pg_rman had to get the correct data for backup.

> Probably it is better to interrupt the restore operation while sending an ERROR message instead of WARNING.

I do not think it is better, because the user loses the way to recover from backup if the pg_control of the current instance is broken.
In case of recovery, pg_rman should extract all information for recovery the database from the backup. However, it seems complex. ( because of compressed backup... )

**Comment by egashira-yusuke** [comment]
> Also, if the PostgreSQL's DEFAULT_XLOG_SEG_SIZE is changed in building server, it will assimilate in building pg_rman because DEFAULT_XLOG_SEG_SIZE is defined in PostgreSQL's include file "include/pg_config.h".

I'm sorry, my recognition was wrong...
The DEFAULT_XLOG_SEG_SIZE is not changed in PostgreSQL's server, and the walsegsize is changed in initdb.

However, in recovery task, it does not affect for recovering instance because the value of wal_segment_size is not used for actual task.

I think that below ways are better than always interrupting recovery.
- If the "check" option is specified in recovery, report ERROR and interrupt the task.
- If the "check" option is specified in recovery, show the message about "pg_control is corrupted. pg_rman will use DEFAULT WAL SIZE for checking recovery task".

**Comment by MoonInsung** [comment]
> I'm sorry, my recognition was wrong...
> The DEFAULT_XLOG_SEG_SIZE is not changed in PostgreSQL's server, and the walsegsize is changed in initdb.

Yes. The segement size of wal that I talked about was the size set when initDB work.

> 
> However, in recovery task, it does not affect for recovering instance because the value of wal_segment_size is not used for actual task.

As you said, Yes. it seems that using wal_segment_size only if use the check option when restoring.
Sorry.

> 
> I think that below ways are better than always interrupting recovery.
> 
> * If the "check" option is specified in recovery, report ERROR and interrupt the task.
> * If the "check" option is specified in recovery, show the message about "pg_control is corrupted. pg_rman will use DEFAULT WAL SIZE for checking recovery task".

In other words, if the check option is enabled, it seems better to output an ERROR level log and interrupt the restore check working.

Create a new patch? Or check to other user's opinions?

**Comment by egashira-yusuke** [comment]
I'll create the new patch with considering the check option is enabled.
I think checking other user's opinion should be based on the new patch.

Should I create the new pull request? or, should I push to new commit for this pull request's branch?
(Sorry, I'm not used to using Github.. )

**Comment by MoonInsung** [comment]
> I'll create the new patch with considering the check option is enabled.
> I think checking other user's opinion should be based on the new patch.
Thank you!
First , I agree with your opinion.

> 
> Should I create the new pull request? or, should I push to new commit for this pull request's branch?
> (Sorry, I'm not used to using Github.. )
Whatever's fine!

Best regards.

**Pull request merged**
