### PR TITLE
Ignore invalid backups in show command output.

### LINKED ISSUE #23: Backup problem
Hi. I have problem with backup:
```
2016-04-09 08:01:01  FULL        0m      0B     0  ERROR
2016-04-09 06:30:01  INCR        0m      0B     0  ERROR
2016-04-09 03:30:01  INCR        0m      0B     0  ERROR
2016-04-09 00:30:01  INCR        0m      0B     1  ERROR
2016-04-08 21:30:01  INCR        0m      0B     0  ERROR
2016-04-08 18:30:01  INCR        0m      0B     0  ERROR
2016-04-08 15:30:01  INCR        0m      0B     0  ERROR
2016-04-08 12:30:02  INCR        0m      0B     0  ERROR
2016-04-08 09:30:01  INCR        0m      0B     0  ERROR
2016-04-08 06:30:01  INCR        0m      0B     0  ERROR
2016-04-08 03:30:01  INCR        0m      0B     0  ERROR
2016-04-07 09:30:02  INCR        0m      0B     1  ERROR
2016-04-07 06:30:02  INCR        7m  1723MB     1  OK
2016-04-07 03:30:02  INCR        9m  2733MB     1  OK
2016-04-07 00:30:01  INCR       13m  3426MB     1  OK
2016-04-06 21:30:01  INCR       11m  2744MB     1  OK
2016-04-06 18:30:01  INCR       12m  3122MB     1  OK
2016-04-06 15:30:01  INCR       13m  3715MB     1  OK
2016-04-06 12:30:01  INCR       16m  3919MB     1  OK
2016-04-06 09:30:02  INCR       16m  3837MB     1  OK
2016-04-06 06:30:01  INCR        7m  1547MB     1  OK
2016-04-06 03:30:01  INCR        9m  2342MB     1  OK
2016-04-06 00:30:01  INCR       12m  3428MB     1  OK
2016-04-05 21:30:01  INCR       16m  3188MB     1  OK
2016-04-05 18:30:01  INCR       14m  3819MB     1  OK
2016-04-05 15:30:02  INCR       18m  3911MB     1  OK
2016-04-05 12:30:01  INCR       23m  5613MB     1  OK
2016-04-05 08:01:01  FULL      136m    61GB     1  OK
1970-01-01 01:00:00            ----    ----     0  UNKNOWN
```
I can't remove 1970-01-01 01:00:00
I want remove all errors backups but keep valid

Please help me

### PR DESCRIPTION
**Pull request by amitlan**
Fixes #23 .

### CODE REVIEW

**Comment by bwtakacy** [comment]
Thanks for your PR!

Does this fix make pg_rman ignore invalid backups even if show-all option is specified?
I'm afraid that users cannot find there are such invalid backups to be removed.

**Comment by amitlan** [comment]
Yes, it's independent of `show-all` option.

What I thought is that there is no way for a user to specify an invalid backup to be deleted as the reporter of issue #23 showed.  It makes sense to include backups with other *valid* state exactly because they can be specified; for example, error'd, corrupted, etc.

Actually what I suggest is to extend the `purge` command (in another PR) to clean up not just deleted backups but also these other useless-in-future backups such as errored, corrupted, invalid because we don't need a specification for `purge` command anyway.  Why keep such backups in catalog, right?  Or am I missing some rational behind the command?

**Comment by bwtakacy** [comment]
Ah, I've understood.
I agree with you that the invalid backups are not informative for `show` and need to be removed in `purge`.

So, I think this PR is ok to merge.
Any other comments?

**Comment by amitlan** [comment]
Thanks for merging!

**Comment by ooyamams** [comment]
Sorry for my late response. Thanks @amitlan and @bwtakacy!

**Pull request merged**
