### PR TITLE
Update 1.3.3 for master

### PR DESCRIPTION
**Pull request by kfuru**
I'd like to upgrade pg_rman, so could you merge?

### CODE REVIEW

**Comment by amitlan** [comment]
We need to fix build of master branch with PG version 10.  So, I will merge this PR after that fix has been pushed.

**Comment by amitlan** [comment]
Furutani-san,

You will need to *rebase* your develop_1.3.3 branch against the latest master branch of the main repository.  I just pushed a commit to the master branch that fixes the build error with PG 10dev.

**Comment by kfuru** [comment]
I was a commit to the master,  including fix build errors.

**Comment by amitlan** [comment]
Thanks a lot!

**Pull request merged**
