### PR TITLE
developments for postgresql v14

### PR DESCRIPTION
**Pull request by mikecaat**
TODO

* need review
* check the PostgreSQL release notes

### CODE REVIEW

**Comment by MoonInsung** [comment]
Dear @mikecaat .
Thank you for responding to the PostgreSQL 14.

First, I checked that the modified part(f225e3d) is related to the commit below.

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=67a472d71c98c3d2fa322a1b4013080b20720b98

Other than that(changed in PostgreSQL14), I don't think anything can affect pg_rman.
Also, I tested it in my environment(CentOS7/x86), 
but this PR checked that it usually works in 
the PostgreSQL currently master branch without any problems.
So I want to commit this PR.
If, don't have any opinion, I'll commit it around 16:00(JST) on June 11.

Best regards.
Moon.

**Comment by mikecaat** [comment]
Dear @MoonInsung 

Thanks for reviewing the patches.

Regards,

**Comment by huangfumingyue** [comment]
Thanks for making the patch. It looks good to me.

**Comment by mikecaat** [comment]
Thanks for reviewing!

**Pull request merged**
